version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::324037305216:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-PdSbh2urla1J"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::324037305216:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-oGMfddYFeE3o"
cloudformation_execution_role = "arn:aws:iam::324037305216:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-ABJJVD9zfIQq"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-2ymxrkurke2b"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::324037305216:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-6ahoybCgGag3"
cloudformation_execution_role = "arn:aws:iam::324037305216:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-FInRMJmQqic5"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-pq2us3tcvmzv"
image_repository = ""
region = "us-east-1"
